/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppMultiselect: typeof import('./src/components/AppMultiselect.vue')['default']
    AppPageTitle: typeof import('./src/components/AppPageTitle.vue')['default']
    AppSelect: typeof import('./src/components/AppSelect.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    RehearsalDetails: typeof import('./src/components/RehearsalDetails/RehearsalDetails.vue')['default']
    RehearsalDetailsSection: typeof import('./src/components/RehearsalDetails/RehearsalDetailsSection.vue')['default']
    RehearsalItem: typeof import('./src/components/RehearsalDetails/RehearsalItem.vue')['default']
    RehearsalModal: typeof import('./src/components/RehearsalModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetItem: typeof import('./src/components/SetItem.vue')['default']
    SetlistModal: typeof import('./src/components/SetlistModal.vue')['default']
    ShowItem: typeof import('./src/components/ShowItem.vue')['default']
    ShowModal: typeof import('./src/components/ShowModal.vue')['default']
    SideNavigation: typeof import('./src/components/Navigation/SideNavigation.vue')['default']
    SongItem: typeof import('./src/components/SongItem.vue')['default']
    SongModal: typeof import('./src/components/SongModal.vue')['default']
    SongSection: typeof import('./src/components/RehearsalDetails/RehearsalDetailsSection.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    VenueInfoDisplay: typeof import('./src/components/VenueInfoDisplay.vue')['default']
    VenueItem: typeof import('./src/components/VenueItem.vue')['default']
    VenueModal: typeof import('./src/components/VenueModal.vue')['default']
  }
}
