/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppPagetitle: typeof import('./src/components/AppPagetitle.vue')['default']
    AppPageTitle: typeof import('./src/components/AppPageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetList: typeof import('./src/components/SetList.vue')['default']
    SetlistDisplay: typeof import('./src/components/SetlistDisplay.vue')['default']
    SideNavigation: typeof import('./src/components/SideNavigation/SideNavigation.vue')['default']
    SongListItem: typeof import('./src/components/SongListItem.vue')['default']
    SongModal: typeof import('./src/components/SongModal.vue')['default']
  }
}
