/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/UI/AppButton.vue')['default']
    AppDrawer: typeof import('./src/components/Layout/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    AppPageTitle: typeof import('./src/components/Layout/AppPageTitle.vue')['default']
    AppSelect: typeof import('./src/components/UI/AppSelect.vue')['default']
    DashboardCard: typeof import('./src/components/DashboardCard/DashboardCard.vue')['default']
    DashboardCardStat: typeof import('./src/components/DashboardCard/DashboardCardStat.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    RehearsalDetails: typeof import('./src/components/RehearsalDetails/RehearsalDetails.vue')['default']
    RehearsalDetailsSection: typeof import('./src/components/RehearsalDetails/RehearsalDetailsSection.vue')['default']
    RehearsalModal: typeof import('./src/components/RehearsalModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetDetails: typeof import('./src/components/SetDetails.vue')['default']
    SetlistModal: typeof import('./src/components/SetlistModal.vue')['default']
    ShowDetails: typeof import('./src/components/ShowDetails.vue')['default']
    ShowModal: typeof import('./src/components/ShowModal.vue')['default']
    SideNavigation: typeof import('./src/components/Navigation/SideNavigation.vue')['default']
    SongDetails: typeof import('./src/components/SongDetails.vue')['default']
    SongModal: typeof import('./src/components/SongModal.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    VenueDetails: typeof import('./src/components/VenueDetails.vue')['default']
    VenueInfoDisplay: typeof import('./src/components/VenueInfoDisplay.vue')['default']
    VenueModal: typeof import('./src/components/VenueModal.vue')['default']
  }
}
