/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../core/components/AppButton.vue')['default']
    AppDrawer: typeof import('./../core/components/Layout/AppDrawer.vue')['default']
    AppFooter: typeof import('./../core/components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./../core/components/Layout/AppHeader.vue')['default']
    AppPageTitle: typeof import('./../core/components/Layout/AppPageTitle.vue')['default']
    AppSelect: typeof import('./../core/components/AppSelect.vue')['default']
    DashboardCard: typeof import('./../modules/dashboard/components/DashboardCard.vue')['default']
    DashboardCardStat: typeof import('./../modules/dashboard/components/DashboardCardStat.vue')['default']
    EventCalendar: typeof import('./../modules/show/components/eventCalendar/EventCalendar.vue')['default']
    EventCalendarNavbar: typeof import('./../modules/show/components/eventCalendar/EventCalendarNavbar.vue')['default']
    EventCalendarNavBar: typeof import('./../modules/show/components/eventCalendar/EventCalendarNavBar.vue')['default']
    LoginModal: typeof import('./../core/components/LoginModal.vue')['default']
    RehearsalDetails: typeof import('./../modules/rehearsal/components/RehearsalDetails.vue')['default']
    RehearsalDetailsSection: typeof import('./../modules/rehearsal/components/RehearsalDetailsSection.vue')['default']
    RehearsalModal: typeof import('./../modules/rehearsal/components/RehearsalModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetDetails: typeof import('./../modules/set/components/SetDetails.vue')['default']
    SetlistModal: typeof import('./../modules/setlist/components/SetlistModal.vue')['default']
    ShowCalendar: typeof import('./../modules/show/components/showCalendar/ShowCalendar.vue')['default']
    ShowDetails: typeof import('./../modules/show/components/ShowDetails.vue')['default']
    ShowModal: typeof import('./../modules/show/components/ShowModal.vue')['default']
    SideNavigation: typeof import('./../core/components/Navigation/SideNavigation.vue')['default']
    SongDetails: typeof import('./../modules/song/components/SongDetails.vue')['default']
    SongModal: typeof import('./../modules/song/components/SongModal.vue')['default']
    UserMenu: typeof import('./../core/components/UserMenu.vue')['default']
    VenueDetails: typeof import('./../modules/venue/components/VenueDetails.vue')['default']
    VenueInfoDisplay: typeof import('./../modules/venue/components/VenueInfoDisplay.vue')['default']
    VenueModal: typeof import('./../modules/venue/components/VenueModal.vue')['default']
  }
}
